#数据库配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pilipili
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 120000
  redis:
    port: 6379
    host: localhost
    password: 1234
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 500MB
  application:
    name: pilipili-api
rocketmq:
  name:
    server:
      address: localhost:9876
fdfs:
  tracker-list: localhost:22122
#  文件存储路径（自用）
  http:
    storage-addr: http://localhost:8888/group1/